### ISSUE TITLE
Entity not visible in published scene

### ISSUE THREAD

**Issue by sherinmannambeth** [aws-samples/amazon-sumerian-arcore-starter-app#13]
I have published an AR scene using Amazon Sumerian and used this amazon-sumerian-arcore-starter-app to view the scene. But, when the app is build and run, the entity(Drone or Mannequin) is not visible in my scene. I am not able to find any troubleshooting for this sort of issue.

Followed the below mentioned website for the creation of the scene: - 
https://docs.sumerian.amazonaws.com/tutorials/create/intermediate/augmented-reality-using-sumerian-arcore/

**Comment by mike-starr** [comment]
Please reach out to us on https://slack.sumerian.aws/ for support - we can take a look at your specific scene and figure out what's going on.
